### ISSUE TITLE
Missing requirement of matplotlib in setup.py

### ISSUE THREAD

**Issue by Keynaan** [pyansys/PyMAPDL-reader#40]
Hi @akaszynski,

excuse me to be annoying, but as a follow up to the discussion we had in [pyvista](https://github.com/pyvista/pyvista/issues/1364), I think the requirement of `matplotlib` ist still missing in `setup.py` of `ansys-mapdl-core` and needs to be added as  in [ansys-mapdl-core](https://github.com/pyansys/PyMAPDL/blob/baa251ee49487d598da4a56f626bf1ace3796985/setup.py#L17).

It seems that the addition in [requirements-build.txt](https://github.com/pyansys/PyMAPDL-reader/blob/38a7d454924e19466bdc7b115689af9934ff69f5/requirements_build.txt#L5) is not enough for `pip` to be recognised.

Nonetheless, thank you for your excellent work.
Best regards

```
$ python -m pip install ansys-mapdl-reader
Collecting ansys-mapdl-reader
...
Installing collected packages: pillow, imageio, transforms3d, scooby, meshio, appdirs, vtk, pyvista, tqdm, ansys-mapdl-reader
Successfully installed ansys-mapdl-reader-0.50.15 appdirs-1.4.4 imageio-2.9.0 meshio-4.4.6 pillow-8.2.0 pyvista-0.31.0 scooby-0.5.7 tqdm-4.61.0 transforms3d-0.3.1 vtk-9.0.1

$ python
Python 3.8.6 (default, Apr 15 2021, 08:28:58) 
[GCC 9.2.1 20191120 (Red Hat 9.2.1-2)] on linux
>>> from ansys.mapdl import reader
Traceback (most recent call last):
  File "/opt/fs/linux-centos8-haswell/gcc-9.2.1/python-3.8.6-qbpjqyumg5orxexerjfldkuqaanw7roe/lib/python3.8/site-packages/pyvista/plotting/colors.py", line 396, in get_cmap_safe
    from matplotlib.cm import get_cmap
ModuleNotFoundError: No module named 'matplotlib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/fs/linux-centos8-haswell/gcc-9.2.1/python-3.8.6-qbpjqyumg5orxexerjfldkuqaanw7roe/lib/python3.8/site-packages/ansys/mapdl/reader/__init__.py", line 30, in <module>
    _configure_pyvista()
  File "/opt/fs/linux-centos8-haswell/gcc-9.2.1/python-3.8.6-qbpjqyumg5orxexerjfldkuqaanw7roe/lib/python3.8/site-packages/ansys/mapdl/reader/misc.py", line 141, in _configure_pyvista
    pv.rcParams["cmap"] = "jet"
  File "/opt/fs/linux-centos8-haswell/gcc-9.2.1/python-3.8.6-qbpjqyumg5orxexerjfldkuqaanw7roe/lib/python3.8/site-packages/pyvista/themes.py", line 58, in __setitem__
    setattr(pyvista.global_theme, key, value)
  File "/opt/fs/linux-centos8-haswell/gcc-9.2.1/python-3.8.6-qbpjqyumg5orxexerjfldkuqaanw7roe/lib/python3.8/site-packages/pyvista/themes.py", line 1474, in cmap
    get_cmap_safe(cmap)  # for validation
  File "/opt/fs/linux-centos8-haswell/gcc-9.2.1/python-3.8.6-qbpjqyumg5orxexerjfldkuqaanw7roe/lib/python3.8/site-packages/pyvista/plotting/colors.py", line 398, in get_cmap_safe
    raise ImportError('cmap requires matplotlib')
ImportError: cmap requires matplotlib

$ pipdeptree -p ansys-mapdl-reader
ansys-mapdl-reader==0.50.15
  - appdirs [required: >=1.4.0, installed: 1.4.4]
  - numpy [required: >=1.14.0, installed: 1.19.4]
  - pyvista [required: >=0.30.1, installed: 0.31.0]
    - appdirs [required: Any, installed: 1.4.4]
    - imageio [required: Any, installed: 2.9.0]
      - numpy [required: Any, installed: 1.19.4]
      - pillow [required: Any, installed: 8.2.0]
    - meshio [required: >=4.0.3,<5.0, installed: 4.4.6]
      - numpy [required: Any, installed: 1.19.4]
    - numpy [required: Any, installed: 1.19.4]
    - pillow [required: Any, installed: 8.2.0]
    - scooby [required: >=0.5.1, installed: 0.5.7]
    - transforms3d [required: ==0.3.1, installed: 0.3.1]
    - vtk [required: Any, installed: 9.0.1]
  - tqdm [required: >=4.45.0, installed: 4.61.0]
```

**Comment by akaszynski** [comment]
Added this in #39, and the next release will be built in the next 30 minutes.  Patch will be out in `ansys-mapdl-reader=0.50.16`

**Comment by akaszynski** [comment]
I'll add this in `ansys-mapdl-core` as well.

**Comment by akaszynski** [comment]
Added in both.  Thanks for posting this issue and keeping me informed!

**Comment by Keynaan** [comment]
Thanks alot. :+1:
